- if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then jdk_switcher use "$CUSTOM_JDK"; fi
  
 -before_script: sudo apt-get install build-essential automake1.10 libtool
 +before_script: 
 +  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install build-essential automake1.10 libtool; fi
  
 -script: "mvn install -P linux64"
 +script: 
 +  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then "mvn install -P osx64"; fi
 +  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then "mvn install -P linux64"; fi
  
  after_success:
    - mvn -P linux64 jacoco:report coveralls:report
